name: CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  actions: read
  contents: read

jobs:
  main:
    runs-on: ubuntu-latest
    steps:

      # Cache node_modules
      - uses: actions/setup-node@v4
        with:
          cache-dependency-path: package-lock.json
          node-version: 20
          cache: 'npm'

      - run: npm ci --legacy-peer-deps

      - run: npx nx run-many -- -t lint test build e2
